### ISSUE TITLE
Model Zoo giving 404

### ISSUE THREAD

**Issue by agrawaleshani** [ayanban011/SwinDocSegmenter#1]
Hi, 
Hey can you load the pre-trained models on hugging-face please. 
Also, Can you please provide scripts to how to fine tune it on Custom Dataset, that will be really helpful for my project.

**Comment by ayanban011** [comment]
Hi, Thanks for identifying this issue. The links are updated now and it will be working fine!!!
Regarding the pre-trained model weights, they will be available in the hugging face by next week.
And, for the custom dataset, the instructions will be updated in the readme.md.
For any other query feel free to reach out to us.
