### ISSUE TITLE
Doclaynet Metrics

### ISSUE THREAD

**Issue by nvilia** [ayanban011/SwinDocSegmenter#11]
Thank you for releasing your checkpoints and repo, however I have been having a hard time understanding the doclaynet results. Just looking at Table 6:

| Classes         | MaskRCNN | FasterRCNN | Yolov5 | Ours  |
|-----------------|----------|------------|--------|-------|
| Caption         | 71.5     | 70.1       | 77.7   | **83.56** |
| Footnote        | 71.8     | 73.7       | **77.2**   | 64.82 |
| Formula         | 63.4     | 63.5       | **66.2**   | 62.31 |
| List-item       | 80.8     | 81.0       | **86.2**   | 82.33 |
| Page-footer     | 59.3     | 58.9       | 61.1   | **65.11** |
| Page-header     | 70.0     | **72.0**   | 67.9   | 66.35 |
| Picture         | 72.7     | 72.0       | 77.1   | **84.71** |
| Section-header  | 69.3     | 68.4       | **74.6**   | 66.5  |
| Table           | 82.9     | 82.2       | 86.3   | **87.42** |
| Text            | 85.8     | 85.4       | 88.1   | **88.23** |
| Title           | 80.4     | 79.9       | **82.7**   | 63.27 |
| **Reported All**| **73.5** | **73.4**   | **76.8** | **76.85** |
| **Calculated All** | 73.4 | 73.4      | 76.8  | 74.1 |

For all other methods the reported total coco-mAP (macro) naturally matches averaging the per-class AP as reported (allowing for rounding errors), however for your method there is a very large difference.

Further, using the provided checkpoint and calculating the mAP using your repo, I get a third number of 75.2:

```
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.752
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.916
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.842
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.554
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.654
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.781
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.387
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.795
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.841
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.684
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.786
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.876
 ```

Would you help clarifying which is the correct mAP: 75.2 or 74.1 or 76.85?

Thank you!

**Comment by ayanban011** [comment]
Hi, Thanks for raising the question. With all due respect, I am sorry to write you that I didn't understand the term "very large." The results you have reported are just a difference of 1-2%, which usually happens depending on the hardware, environment, other parameters, and so on.

**Comment by nvilia** [comment]
Thank you for your prompt response! 

"Very large" in the sense that the difference between the reported and calculated mAP, by equally averaging the classes, (76.85 and 74.1) of 2.75 is a larger number itself than the 0.05 difference between convolutional-based Yolov5 and SwinDocSegmenter, which by your own words is a significant margin: 

>  From Table 6 we conclude that our proposed SwinDocSegmenter outperforms the convolutional-based algorithms (MaskRCNN, FasterRCNN, etc.) by a significant margin.

I was just trying to understand if perhaps some of the per-class APs reported in the table have a typo? The average of the 11 classes should really match the number for *All* at least to 1 decimal place.

**Comment by ayanban011** [comment]
I can't remember the table has a typo or not. Maybe it has. I will recheck and update the in the ArXiV. Still I don't agree with your "very large" word. There is difference between significant margin and very large. I am not saying that I am 100% correct. We release the weights so the people can use it their own work. May be it doesn't exactly same the results are reported in the paper. It depends on the hardware, python, torch version, environment and so on. I think this discussion is not going in the write direction. So if you agree I will close this issue.

**Comment by nvilia** [comment]
Sure, if you don't mind checking the averaging of the classes in Table 6 that would be appreciated! Feel free to close, and thank you for providing the checkpoint and being responsive on Github.

**Comment by ayanban011** [comment]
Thanks. I will check it.
