### ISSUE TITLE
How to Run Inference?

### ISSUE THREAD

**Issue by Mukilan-Krishnakumar** [ayanban011/SwinDocSegmenter#3]
I went through the `demo.ipynb` file. I have been running it using colab. 

After installing all the dependencies, in the code, we finally get to inference. 

```
register_coco_instances("prima_val",{},"/content/drive/MyDrive/layout-model-training-master/layout-model-training-master/tools/annotations-val.json","/content/drive/MyDrive/layout-model-training-master/layout-model-training-master/data/prima/val")
```

As you can observe, you have given your own colab drive link, which is not accessible by anyone else. Either share the folder or make it public. Also, please add more documentation for running inference on a single image.

**Comment by TimHunt12** [comment]
I am having similar problems.  I found that if I went into the .yaml files I could revise the directories for the data output and that got me a little further, but I am having an issue getting the pre trained checkpoint, which I'll submit in a new thread.

It is troubling that it has been over a month and no one has responded to your issue above.

**Comment by TimHunt12** [comment]
I am having similar problems.  I found that if I went into the .yaml files I could revise the directories for the data output and that got me a little further, but I am having an issue getting the pre trained checkpoint, which I'll submit in a new thread.

It is troubling that it has been over a month and no one has responded to your issue above.

**Comment by ayanban011** [comment]
> I went through the `demo.ipynb` file. I have been running it using colab.
> 
> After installing all the dependencies, in the code, we finally get to inference.
> 
> ```
> register_coco_instances("prima_val",{},"/content/drive/MyDrive/layout-model-training-master/layout-model-training-master/tools/annotations-val.json","/content/drive/MyDrive/layout-model-training-master/layout-model-training-master/data/prima/val")
> ```
> 
> As you can observe, you have given your own colab drive link, which is not accessible by anyone else. Either share the folder or make it public. Also, please add more documentation for running inference on a single image.

Hi, you have to download the dataset and put it on your own google drive. The dataset link is here. https://www.primaresearch.org/datasets/Layout_Analysis. Also, detectron2 always allow the inference on the entire test set for custom models not on single image.
