### ISSUE TITLE
How to do Inference

### ISSUE THREAD

**Issue by TimHunt12** [ayanban011/SwinDocSegmenter#6]
I now have the model running and it does the evaluation fine.

I am using publaynet as the base model.

I would like to upload a new image and have the model predict the regions of the image that fit each of the categories, text, title, list, table and figure.

I have gone through the readmes and the code and I don't see anywhere where I can load an image and get an inference.  

Where is it or do I need to build that myself?

Thanks.

**Comment by ayanban011** [comment]
I have updated the ReadMe. I hope it helps.

**Comment by TimHunt12** [comment]
Thanks I'll check it out.

**Comment by 00sapo** [comment]
Hi, I was testing out your project and I've created a little script for doing it: https://github.com/00sapo/SwinDocSegmenter-tests/blob/main/test.py

**Comment by ayanban011** [comment]
I have just one suggestion change the number of classes from 6 to 11, then it will be more robust. Use the doclaynet class and their corresponding weights.

**Comment by 00sapo** [comment]
> I have just one suggestion change the number of classes from 6 to 11, then it will be more robust. Use the doclaynet class and their corresponding weights.

Thanks, I tried, but the results are not encouraging because the provided configs do not match the trained weights. There are some layers that are not loaded properly... For PRIMA, just changing the number of feed-forward units fixed the issue, for DocLayNet, there are other configs to fix as well.

**Comment by ayanban011** [comment]
Thanks for trying and reporting the issue. I think this issue has been resolved. So I am closing this.
