### ISSUE TITLE
HJ dataset model link in model zoo is wrong.

### ISSUE THREAD

**Issue by GT-KIM** [ayanban011/SwinDocSegmenter#7]
Hello,
Thanks for sharing your wonderful research!

Unfortunately, I think the model link for HJ dataset is the same as Prima's.
According to the filename, the model for HJ dataset has the wrong link.

Best,

**Comment by ayanban011** [comment]
Thanks for reaching out. We are really sorry for our mistake. The link is updated in the Readme.md.
